name: Run Installation Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: davhofer/py2spack-spack-installation-test:latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python package and dependencies
        run: python -m pip install .[tests]

      - name: Check PYTHONPATH
        run: echo $PYTHONPATH

      - name: Check SPACK_ROOT
        run: echo $SPACK_ROOT

      - name: Run tests
        run: python -m pytest
